### ISSUE TITLE
Get HTTP request not working on client side

### ISSUE THREAD

**Issue by Y-Negash** [Aebel-Shajan/nemo-movies#7]
**Expected:**
After 'npm start' the web page should be blank and in the console the data from the get request (the movies) should show up as an array.

**Actual:**
The page is blank but so is the console. 

This could be because of the baseURL in the axiosConfig.js but further investigation is needed.

**Comment by Y-Negash** [comment]
**Update:**
Console is no longer blank. It was a syntax error but instead of showing the movies data, there is now an Axios 'Network Error'. This seems to be a CORS policy restriction and as a result the get request is being blocked.

**Comment by Y-Negash** [comment]
**Final Update with Solution:**
After adding a CORs Configurer in the backend, the get request is no longer blocked.

**Comment by Aebel-Shajan** [comment]
Nice one g
